name: proximitreats
description: "The Proximitreats Flutter application."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  get_it: ^9.2.0
  injectable: ^2.7.1+2
  proximitreats_client:
    path: ../proximitreats_client
  serverpod_flutter: ^3.1.1
  serverpod_auth_idp_flutter: ^3.1.1
  go_router: ^17.0.1
  listenable_widget: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.11.1
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
